### ISSUE TITLE
[GSsoc'23] Duplicate Instagram icons in Chef's section

### ISSUE THREAD

**Issue by Yashika-Agrawal** [Anupkjha2601/food-recipes-website#161]
The chef section has duplicate Instagram icon with one not working.
![image](https://github.com/Anupkjha2601/food-recipes-website/assets/97408966/727193b1-1876-42c7-88fb-065574718c13)
I would like to work on this issue, please assign me under GSsoc'23.

**Comment by srjbisht01** [comment]
I want to remove the duplicate icon and during correcting the alignment I have done this. so please assign this to me.
I have done this one. Please give me a chance to update this. undet the tag of
#gssoc'23 tag

**Comment by goodchai0** [comment]
@Yashika-Agrawal I am assigning this to you!! are you free to work on this?

**Comment by Yashika-Agrawal** [comment]
Yes , I am free to work on this.

**Comment by srjbisht01** [comment]
Hey @Yashika-Agrawal !
I just want to let you know that this issue only contain duplicacy of instagram icon. As I have seen that you have also added hover effect in the icons. 
So if you could by any chance update your pr because I have assigned a issue for hover effect in this particular section. so that by this we both can have a chance to merge our code.

**Comment by bilalshaikh292** [comment]
heyy is the issue still open ?

**Comment by Yashika-Agrawal** [comment]
@bilalshaikh292 Nope , it is merged

**Comment by bilalshaikh292** [comment]
Isn't it Taking Too long To complete ? it is not that big Issue

**Comment by Yashika-Agrawal** [comment]
@bilalshaikh292 it is already completed and merged.

**Comment by bilalshaikh292** [comment]
Is there any another issue i can work on
